
% Create a ROS 2 node
node = ros2node("/matlab_node");

sub = ros2subscriber( ...
    node, ...
    "/vrpn_mocap/bod1/pose", ...
    "geometry_msgs/PoseStamped", ...
    "Reliability","besteffort");

msg = receive(sub, 2);